AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    Runtime: java8
    MemorySize: 256

Resources:

  RestApi:
    Type: AWS::Serverless::Api # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      StageName: prod

  CreateHomebowdataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/HelloWorld-1.0.jar
      Handler: helloworld.HomebowdataHandler::create
      Policies:
        DynamoDBCrudPolicy:
          TableName:
            Ref: HomebowdataTable
      Events:
        List:
          Type: Api
          Properties:
            Path: /Homebowdata
            Method: POST
            RestApiId:
              Ref: RestApi

  GetHomebowdataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/HelloWorld-1.0.jar
      Handler: helloworld.HomebowdataHandler::read
      Policies:
        DynamoDBReadPolicy:
          TableName:
            Ref: HomebowdataTable
      Events:
        List:
          Type: Api
          Properties:
            Path: /Homebowdata/{mlsId}
            Method: GET
            RestApiId:
              Ref: RestApi

  ListAllHomebowdataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/HelloWorld-1.0.jar
      Handler: helloworld.HomebowdataHandler::getAll
      Policies:
        DynamoDBReadPolicy:
          TableName:
            Ref: HomebowdataTable
      Events:
        List:
          Type: Api
          Properties:
            Path: /Homebowdata
            Method: GET
            RestApiId:
              Ref: RestApi

  UpdateHomebowdataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/HelloWorld-1.0.jar
      Handler: helloworld.HomebowdataHandler::update
      Policies:
        DynamoDBReadPolicy:
          TableName:
            Ref: HomebowdataTable
      Events:
        List:
          Type: Api
          Properties:
            Path: /Homebowdata/{mlsId}
            Method: PUT
            RestApiId:
              Ref: RestApi

  DeleteHomebowdataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/HelloWorld-1.0.jar
      #CodeUri: ./
      Handler: helloworld.HomebowdataHandler::delete
      Role: !GetAtt HomebowdataCRUDRole.Arn
      Policies:
        DynamoDBReadPolicy:
          TableName:
            Ref: HomebowdataTable
      Events:
        List:
          Type: Api
          Properties:
            Path: /Homebowdata/{mlsId}
            Method: DELETE
            RestApiId:
              Ref: RestApi

  #  GetPropertyFunction:
  #    Type: AWS::Serverless::Function
  #    Properties:
  #      CodeUri: target/HelloWorld-1.0.jar
  #      #CodeUri: ./
  #      Handler: map.getProperty::handleRequest
  #      Policies:
  #        DynamoDBReadPolicy:
  #          TableName:
  #            Ref: GeoTable
  #      Events:
  #        List:
  #          Type: Api
  #          Properties:
  #            Path: /Map/{latitude&longitude}
  #            Method: GET
  #            RestApiId:
  #              Ref: RestApi

  HomebowdataTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName:
        Fn::Sub: homebowdata
      PrimaryKey:
        Name: mlsId
        Type: String

  #  GeoTable:
  #    Type: AWS::Serverless::SimpleTable
  #    Properties:
  #      TableName:
  #        Fn::Sub: GeoTable
  #      PrimaryKey:
  #        Name: id
  #        Type: String

  #https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html
  HomebowdataCRUDRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: VisualEditor0
                Effect: Allow
                Action: dynamodb:*
                Resource:
                  -
                    arn:aws:dynamodb:us-west-1:635341036773:table/homebowdata
                    arn:aws:dynamodb:us-west-1:635341036773:table/homebowdata/index/*

Outputs:

  RestApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://RestApi.execute-api.${AWS::Region}.amazonaws.com/Prod/homebowdata/"
  CreateHomebowdataFunction:
    Description: "CreateHomebowdataFunctionARN"
    Value: !GetAtt CreateHomebowdataFunction.Arn
  CreateHomebowdataIamRole:
    Description: "Implicit IAM Role created for CreateHomebowdataFunction"
    Value: !GetAtt CreateHomebowdataFunctionRole.Arn
  CetHomebowdataFunction:
    Description: "GetHomebowdataFunctionARN"
    Value: !GetAtt GetHomebowdataFunction.Arn
  GetHomebowdataFunctionIamRole:
    Description: "Implicit IAM Role created for GetHomebowdataFunction"
    Value: !GetAtt GetHomebowdataFunctionRole.Arn
  UpdateHomebowdataFunction:
    Description: "UpdateHomebowdataFunctionARN"
    Value: !GetAtt UpdateHomebowdataFunction.Arn
  UpdateHomebowdataFunctionIamRole:
    Description: "Implicit IAM Role created for UpdateHomebowdataFunction"
    Value: !GetAtt UpdateHomebowdataFunctionRole.Arn
  DeleteHomebowdataFunction:
    Description: "DeleteHomebowdataFunctionARN"
    Value: !GetAtt DeleteHomebowdataFunction.Arn

#      Runtime: java8
#      MemorySize: 512
#      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
#        Variables:
#          PARAM1: VALUE
#      Events:
#        HelloWorld:
#          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
#          Properties:
#            Path: /hello
#            Method: get

#Outputs:
#  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
#  # Find out more about other implicit resources you can reference within SAM
#  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
#  HelloWorldApi:
#    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
#    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
#  HelloWorldFunction:
#    Description: "Hello World Lambda Function ARN"
#    Value: !GetAtt HelloWorldFunction.Arn
#  HelloWorldFunctionIamRole:
#    Description: "Implicit IAM Role created for Hello World function"
#    Value: !GetAtt HelloWorldFunctionRole.Arn
